glide:
  enabled: false
  ratio: 0.00007
notes_file: './data/notes.csv'
keys:
  - "a"
  - "s"
  - "d"
  - "f"
  - "g"
  - "h"
  - "j"
  - "k"
  - "l"
  - ";"
notes:
  - "C3"
  - "D3"
  - "E3"
  - "F3"
  - "G3"
  - "A3"
  - "B3"
  - "C4"
  - "D4"
  - "E4"