glide_ratio: 0.00007
notes_file: './data/notes.csv'
keys:
  - "a"
  - "s"
  - "d"
  - "f"
  - "g"
  - "h"
  - "j"
  - "k"
  - "l"
# frequencies:
#   - 261.63
#   - 293.66
#   - 329.63
#   - 349.23
#   - 392.0
#   - 440.0
#   - 493.88
#   - 523.25
#   - 587.33
notes:
  - "C3"
  - "D3"
  - "E3"
  - "F3"
  - "G3"
  - "A3"
  - "B3"
  - "C4"
  - "D4"